apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app2
  namespace: dev
spec:
  releaseName: app2
  interval: 1m
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: app-helm
        namespace: flux-system
      interval: 1m
      valuesFiles:
        sourceRef:
        - kind: GitRepository
          name: app-helm
          file:  ./values/app2.yaml